"use client";

import { CommonHero } from "@/components/CommonHero";

export default function Privacy() {
  return (
    <section className="pb-40">
      {/* Hero Section */}
      <section className="bg-studycrest-11 max-h-full lg:max-h-full pb-10">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8">
          <CommonHero
            title="Privacy"
            description="Our Privacy Policy"
            stretch={true}
          />
        </div>
      </section>

      <section className="container mx-auto px-4 sm:px-6 lg:px-8 mt-10">
        <p className="leading-[30px]">
          <span className="font-semibold">CrestStudy</span> is committed to
          protecting your privacy. This Privacy Policy explains how your
          personal information is collected, used, and disclosed by CrestStudy.
          This Privacy Policy applies to our app, and its associated subdomains
          (collectively, our “Service”) alongside our application, CrestStudy.
          By accessing or using our Service, you signify that you have read,
          understood, and agree to our collection, storage, use, and disclosure
          of your personal information as described in this Privacy Policy and
          our Terms of Service.
        </p>

        <div className="mt-5">
          <h2 className="text-[20px] font-bold">
            1. Definitions and key terms
          </h2>
          <p className="leading-[30px] pt-2">
            To help explain things as clearly as possible in this Privacy
            Policy, every time any of these terms are referenced, are strictly
            defined as:
          </p>
          <p className="leading-[30px] pt-2">
            <span className="font-semibold">Cookie:</span> small amount of data
            generated by a website and saved by your web browser. It is used to
            identify your browser, provide analytics, remember information about
            you such as your language preference or login information.
          </p>
          <p className="leading-[30px] pt-2">
            <span className="font-semibold">Company:</span> when this policy
            mentions “Company,” “we,” “us,” or “our,” it refers to CRESTSTUDY
            LTD, (Yaba, Lagos), that is responsible for your information under
            this Privacy Policy.
          </p>
          <p className="leading-[30px] pt-2">
            <span className="font-semibold">Country:</span> where CrestStudy or
            the owners/founders of CrestStudy are based, in this case is Nigeria
          </p>
          <p className="leading-[30px] pt-2">
            <span className="font-semibold">Customer:</span> refers to the
            company, organization or person that signs up to use the CrestStudy
            Service to manage the relationships with your consumers or service
            users.
          </p>
          <p className="leading-[30px] pt-2">
            <span className="font-semibold">Device:</span> any internet
            connected device such as a phone, tablet, computer or any other
            device that can be used to visit CrestStudy and use the services.
          </p>
          <p className="leading-[30px] pt-2">
            <span className="font-semibold">IP address: </span> Every device
            connected to the Internet is assigned a number known as an Internet
            protocol (IP) address. These numbers are usually assigned in
            geographic blocks. An IP address can often be used to identify the
            location from which a device is connecting to the Internet.
          </p>
          <p className="leading-[30px] pt-2">
            <span className="font-semibold">Personal Data: </span>
            any information that directly, indirectly, or in connection with
            other information — including a personal identification number —
            allows for the identification or identifiability of a natural
            person.
          </p>
          <p className="leading-[30px] pt-2">
            <span className="font-semibold">Service:</span> refers to the
            service provided by CrestStudy as described in the relative terms
            (if available) and on this platform.
          </p>
          <p className="leading-[30px] pt-2">
            <span className="font-semibold">Third-party service: </span>
            refers to advertisers, contest sponsors, promotional and marketing
            partners, and others who provide our content or whose products or
            services we think may interest you.
          </p>
          <p className="leading-[30px] pt-2">
            <span className="font-semibold">App/Application: </span>
            CrestStudy app, refers to the SOFTWARE PRODUCT identified above.
          </p>
          <p className="leading-[30px] pt-2">
            <span className="font-semibold">You:</span> a person or entity that
            is registered with CrestStudy to use the Services
          </p>
        </div>

        <div className="mt-5">
          <h2 className="text-[20px] font-bold">
            2. What Information Do We Collect?
          </h2>
          <p className="leading-[30px] pt-2">
            We collect different types of information to provide and improve our
            Services to you.
          </p>

          <div className="pt-3">
            <p className="text-[17px] font-bold">2.1 Personal Information</p>
            <p className="leading-[30px] pt-2">
              When you register for CrestStudy, we may ask for personally
              identifiable information that includes, but is not limited to:
            </p>
            <p className="leading-[30px] pt-2">- Name</p>
            <p className="leading-[30px] pt-2">- Email Address</p>
            <p className="leading-[30px] pt-2">
              - Academic information (e.g., course of study, institution, study
              habits)
            </p>
            <p className="leading-[30px] pt-2">- Profile picture (optional)</p>
          </div>

          <div className="pt-3">
            <p className="text-[17px] font-bold">2.2 Usage Data</p>
            <p className="leading-[30px] pt-2">
              We automatically collect data about how our Services are accessed
              and used, including:
            </p>
            <p className="leading-[30px] pt-2">
              - Device and browser information
            </p>
            <p className="leading-[30px] pt-2">- IP address</p>
            <p className="leading-[30px] pt-2">
              - Usage patterns, such as the pages visited, features used, and
              interactions within the app
            </p>
          </div>

          <div className="pt-3">
            <p className="text-[17px] font-bold">
              2.3 Cookies and Tracking Technologies
            </p>
            <p className="leading-[30px] pt-2">
              We use cookies and similar tracking technologies to track the
              activity on our Services and store certain information. You can
              choose to disable cookies, but this may limit your use of some
              features.
            </p>
          </div>
        </div>

        <div className="mt-5">
          <h2 className="text-[20px] font-bold">
            3. How We Use Your Information
          </h2>
          <p className="leading-[30px] pt-2">
            CrestStudy uses the information we collect in the following ways:
          </p>
          <p className="leading-[30px] pt-2">
            <span className="font-bold">To Provide and Improve Services:</span>{" "}
            We use your data to deliver the core functionality of our app,
            including managing your profile, tracking study habits, and
            providing tailored recommendations.
          </p>
          <p className="leading-[30px] pt-2">
            <span className="font-bold">To Communicate:</span> We may send you
            notifications, updates, and promotional information. You can manage
            your communication preferences in your settings.
          </p>
          <p className="leading-[30px] pt-2">
            <span className="font-bold">To Personalize Your Experience:</span>{" "}
            We may use data to personalize the content and recommendations
            within the app based on your academic background and usage.
          </p>
          <p className="leading-[30px] pt-2">
            <span className="font-bold">For Analytics:</span> We analyze usage
            data to understand trends, improve the performance of our Services,
            and enhance user experience.
          </p>
        </div>

        <div className="mt-5">
          <h2 className="text-[20px] font-bold">
            4. How We Share Your Information
          </h2>
          <p className="leading-[30px] pt-2">
            We do not sell or rent your personal information. However, we may
            share your data in certain situations:
          </p>
          <p className="leading-[30px] pt-2">
            <span className="font-bold">Service Providers:</span> We work with
            third-party providers who assist us in operating and maintaining the
            Services. These providers are bound by data privacy agreements to
            protect your information.
          </p>
          <p className="leading-[30px] pt-2">
            <span className="font-bold">Legal Compliance:</span> We may disclose
            information if required by law or to protect the safety and rights
            of our users or the public.
          </p>
          <p className="leading-[30px] pt-2">
            <span className="font-bold">Business Transfers:</span> - In the
            event of a merger, acquisition, or asset sale, your personal data
            may be transferred. You will be notified if your data becomes
            subject to a different privacy policy.
          </p>
        </div>

        <div className="mt-5">
          <h2 className="text-[20px] font-bold">5. Data Security</h2>
          <p className="leading-[30px] pt-2">
            We take reasonable precautions to protect your information from
            unauthorized access, disclosure, alteration, or destruction.
            However, no method of transmission or storage is 100% secure. We
            cannot guarantee absolute security but strive to use commercially
            acceptable means to protect your data.
          </p>
        </div>

        <div className="mt-5">
          <h2 className="text-[20px] font-bold">6. Your Choices and Rights</h2>
          <p className="leading-[30px] pt-2">You have the right to:</p>
          <p className="leading-[30px] pt-2">
            <span>Access and Update:</span> Review and update your personal
            information in your account settings.
          </p>
          <p className="leading-[30px] pt-2">
            <span>Delete:</span> Request the deletion of your account and data.
            Some data may be retained for legal or business purposes.
          </p>
          <p className="leading-[30px] pt-2">
            <span>Withdraw Consent:</span> If you previously consented to
            certain data processing, you can withdraw that consent at any time.
          </p>
        </div>

        <div className="mt-5">
          <h2 className="text-[20px] font-bold">7. Children's Privacy</h2>
          <p className="leading-[30px] pt-2">
            <span className="font-bold">CrestStudy</span> is not intended for
            children under the age of 13. We do not knowingly collect personal
            information from children. If we become aware of any data collected
            from children under 13 without verified parental consent, we will
            take steps to remove that information.
          </p>
        </div>

        <div className="mt-5">
          <h2 className="text-[20px] font-bold">
            8. Changes to This Privacy Policy
          </h2>
          <p className="leading-[30px] pt-2">
            We may update our Privacy Policy from time to time. We will notify
            you of any changes by posting the new Privacy Policy on this page
            and updating the “Last Updated” date. We encourage you to review
            this Privacy Policy periodically for any changes.
          </p>
        </div>

        <div className="mt-5">
          <h2 className="text-[20px] font-bold">9. Contact Us</h2>
          <p className="leading-[30px] pt-2">
            Don't hesitate to contact us if you have any questions.
          </p>
          <p className="leading-[30px] pt-2">
            - Email:{" "}
            <span className="text-studycrest-primary">
              contact@creststudy.com
            </span>
          </p>
          <p className="leading-[30px] pt-2">- Phone Number: +2349027968378</p>
          <p className="leading-[30px] pt-2">
            - Link: https://www.creststudy.com/contact
          </p>
        </div>

        <p className="pt-10">
          This Privacy Policy was created to comply with general privacy
          practices and should be reviewed with legal counsel to ensure it meets
          applicable laws and regulations.
        </p>
      </section>
    </section>
  );
}
